[package]
name = "ggez-ball"
version = "0.1.0"
edition = "2024"

[dependencies]
# ggez = "0.10.0"
ggez = { version = "~0.10.0", default-features = false, features = ["gamepad"] }
rand = "~0.10.2"

# glam="0.32.1"
#
# glam="0.33.2"
#

[profile.dev]
opt-level = 1

[profile.release]
lto = true
opt-level = 2
strip = true
debug = false
panic = "abort"
